[project]
name = "Hubbard-Brook-Stream-Chemistry"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.2",
    "scipy>=1.11.4",
    "jupyter>=1.0.0",
    "matplotlib>=3.8.0",
    "scikit-learn>=1.3.1",
    "seaborn>=0.13.0",
    "openpyxl>=3.1.2",
]
